### ISSUE TITLE
parser5

### ISSUE THREAD

**Issue by jayantsinghxyz** [kurttheviking/html2plaintext#10]
Hello, the library is not working in react native due to an issue I tracked down to the parser5 module's streaming section.

**Comment by shuiRong** [comment]
same situation

**Comment by junosuarez** [comment]
yes, please use [cheerio](https://npm.im/cheerio) or another solution instead.

**Comment by kurttheviking** [comment]
closing because it seems alternative solutions provided are better for react-native settings; thank you!
