### ISSUE TITLE
There is still new line

### ISSUE THREAD

**Issue by ycjcl868** [kurttheviking/html2plaintext#8]
There is still new line.

```js
var html2plaintext = require("html2plaintext")
html2plaintext('<p>wqefqwef</p><p>wefq</p><p>qwef</p><p>qew</p><p>fweq</p><p>f</p><p>qwf</p>').trim()

expected:
wqefqwef wefq qwef qew fweq f qwf
```

![image](https://user-images.githubusercontent.com/13595509/43825034-31705652-9b26-11e8-984e-7f97256c4fcd.png)

**Comment by kurttheviking** [comment]
per the current implementation this is expected behavior
